import socket
import threading
from crypto_utils import *

TCP_PORT = 5000
UDP_PORT = 5001
BUFFER_SIZE = 4096					#bigger buffer for IV and ciphertext

#global variables used by GUI; set while connecting
sock = None						#TCP socket connected to the server
aes_key = None						#AES key generated by the client
message_callback = None					#GUI's function for displaying a message
current_username = None				

#registers the GUI function that will be called whenever a new message is received
def set_message_callback(func):
    global message_callback
    message_callback = func


def listen_tcp():
    global sock, aes_key, message_callback

    while True:
        try:
            data = sock.recv(BUFFER_SIZE)			#blocking call (doesn't consume CPU)
            if not data:
                break

            msg = aes_decrypt(aes_key, data)

            if message_callback:
                message_callback(msg)

        except:
            break



def send_message(msg):
    global sock, aes_key, current_username

    if not sock or not aes_key:					#checks if it is connected
        return

    full_message = f"{current_username}: {msg}"
    encrypted = aes_encrypt(aes_key, full_message)
    sock.send(encrypted)



def connect_to_server(server_ip, username):
    global sock, aes_key, current_username
    current_username = username

    #server discovery
    udp_sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    udp_sock.settimeout(1)
    udp_sock.sendto(b"HELLO_SERVER", (server_ip, UDP_PORT))
    try:
        udp_sock.recvfrom(1024)
    except:
        pass 

    #TCP connection
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((server_ip, TCP_PORT))

    #receives public RSA key
    public_bytes = sock.recv(BUFFER_SIZE)
    server_public_key = load_public_key(public_bytes)

    aes_key = generate_aes_key()
    encrypted_aes = rsa_encrypt(server_public_key, aes_key)
    sock.send(encrypted_aes)

    #starts the thread for listening for messages
    threading.Thread(target=listen_tcp, daemon=True).start()

    return True						#connection has been successfully established
